[en]
	title		= "Proven methods, experienced trainers"
	layout		= "inserts/text2-picture1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-training-10.jpg"
	description	= "The methods and techniques we teach are the ones we use every day to produce memorable presentations for business leaders, so we know they work. Our trainers all have many years of experience of high-level presentations so you are learning from true experts."

[es]
	title		= "Metodología probada, formadores experimentados"
	layout		= "inserts/text2-picture1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-training-10.jpg"
	description	= "Los métodos y técnicas que enseñamos son los mismos que utilizamos diariamente para crear presentaciones memorables para nuestros clientes, por lo que sabemos que funcionan. Nuestros formadores suman decenas de años de experiencia en la preparación y exposición de presentaciones de alto nivel, de forma que aprenderás de auténticos expertos."

[fr]
	title		= "Méthodes modernes, formateurs expérimentés"
	layout		= "inserts/text2-picture1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-training-10.jpg"
	description	= "Les méthodes et techniques que nous enseignons sont celles que nous utilisons chaque jour pour créer des présentations mémorables pour les dirigeants d’entreprise. Nos formateurs ont tous plusieurs années d’expérience des présentations de haut niveau. Vous apprendrez avec de vrais experts."
