[en]
	title		= "3 PowerPoint presentation"
	layout		= "inserts/storyline-picture-text.html"
	style		= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-63.jpg"
	description	= "Once the story is validated we build the PowerPoint Deck. We also use Apple Keynote."

[es]
	title		= "3 Validación"
	layout		= "inserts/storyline-picture-text.html"
	style		= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-63.jpg"
	description	= "Nuestro precio incluye tres revisiones de la entrega inicial. Además probamos la presentación en el SO que utilices (Windos, macOS, iOS)"

[fr]
	title		= "3 Présentation PowerPoint"
	layout		= "inserts/storyline-picture-text.html"
	styl			= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-63.jpg"
	description	= "Une fois l'histoire validée nous la mettons en image et nous l'animons avec Microsoft PowerPoint. Nous utilisons également Apple Keynote."

[it]
	title		= "3 Validazione"
	layout		= "inserts/storyline-picture-text.html"
	style		= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-63.jpg"
	description	= "Il nostro prezzo include tre revisioni della  Presentazione iniziale. Testiamo la tua presentazione sul tuo OS di riferimento (Windows, macOS, iOS)"