[en]
	title		= "iStockPhoto purchases included"
	layout		= "inserts/picture1-text2.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-53.jpg"
	description = "You don't have to worry about the cost of purchasing stock pictures. They are included in the price."

[es]
	title		= "Compras de iStockPhoto incluidas"
	layout		= "inserts/picture1-text2.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-53.jpg"
	description	= "No tendrás que preocuparte por el coste de los bancos de imágenes. Están incluidas en el precio."

[fr]
	title		= "iStockPhoto inclus"
	layout		= "inserts/picture1-text2.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-53.jpg"
	description	= "Vous n'avez à vous soucier de rien. L'achat des images nécessaires est inclus dans le prix de la prestation."

[it]
	title		= "L’acquisto di iStockPhoto è incluso"
	layout		= "inserts/picture1-text2.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-53.jpg"
	description	= "Non devi preoccuparti del costo di acquisto delle immagini di stock. Sono incluse nel prezzo."