[en]
	title		= "2 Story"
	layout		= "inserts/storyline-picture-text.html"
	style		= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-62.jpg"
	description	= "Based on the brief and brainstorm we will craft a story that will make your audience want to listen."

[es]
	title		= "2 Creación de la Presentación"
	layout		= "inserts/storyline-picture-text.html"
	style		= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-62.jpg"
	description	= "Tras validar el diseño construiremos la primera versión de las slides en formato PowerPoint. También trabajamos con Apple Keynote."

[fr]
	title		= "2 Histoire"
	layout		= "inserts/storyline-picture-text.html"
	style		= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-62.jpg"
	description	= "Sur base du brief et du brainstorm nous créons une histoire qui donnera envie d'écouter à votre audience."

[it]
	title		= "2 Creazione della Presentazione"
	layout		= "inserts/storyline-picture-text.html"
	style		= "bg-light"
	picture		= "/img/inserts/presentation-creation-service-62.jpg"
	description	= "Una volta che il design è stato approvato costruiamo la prima versione del PowerPoint Deck. In alternativa usiamo anche Keynote di Apple."