[en]
	title		= "Light as a feather"
	layout		= "inserts/picture2-text1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-55.jpg"
	description	= "You want to send your presentation but the file is too big? We will use our in-house tool to reduce the size of the PowerPoint presentation dramatically without visible quality loss."

[es]
	title		= "Ligera como una pluma"
	layout		= "inserts/picture2-text1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-55.jpg"
	description	= "¿Quieres enviar tu presentación pero el archivo es demasiado grande? Con nuestra herramienta propietaria reduciremos drásticamente el tamaño del archivo PowerPoint sin pérdida visible de calidad."

[fr]
	title		= "Légère comme une plume"
	layout		= "inserts/picture2-text1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-55.jpg"
	description	= "Nous réduisons la taille des présentations avec notre outil interne de compression, pour en faciliter la distribution."

[it]
	title		= "Leggero come una piuma"
	layout		= "inserts/picture2-text1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-55.jpg"
	description	= "Vuoi spedire la tua presentazione ma il tuo file è troppo pesante? Useremo il nostro software interno per ridurre enormemente le dimensioni della presentazione PowerPoint, evitando una visibile perdita di qualità."