[en]
	title		= "Meant for Business"
	layout		= "inserts/text2-picture1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-52.jpg"
	description	= "Our Presentation Creation team is led by former business executives who can help you turn complex concepts into simple illustrations. We know how to capture and keep the audience's interest to help you win the day."

[es]
	title		= "Centrado en Empresas"
	layout		= "inserts/text2-picture1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-52.jpg"
	description	= "Nuestro equipo de Creación de Presentaciones está dirigido por antiguos ejecutivos que pueden ayudar a convertir conceptos complejos en sencillas ilustraciones. Son expertos en conseguir despertar el interés de la audiencia para que logres tus objetivos."

[fr]
	title		= "Pour les entreprises"
	layout		= "inserts/text2-picture1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-52.jpg"
	description	= "Notre équipe de création de présentations est dirigée par des personnes connaissant bien le monde de l'entreprise. Ils vous aideront à créer des illustrations simples pour expliquer des concepts complexes."

[it]
	title		= "Pensata per il Business"
	layout		= "inserts/text2-picture1.html"
	style		= "bg-white"
	picture		= "/img/inserts/presentation-creation-service-52.jpg"
	description	= "Il nostro team creativo è guidato da business executive che possono aiutarti a trasformare dei concetti complessi in illustrazioni semplici.Sanno come catturare l’interesse dell’audience ad aiutarvi ad ottenere il risultato."