
# redirect language (only from homepage, don't redirect on subpages)

[[redirects]]
	from			= "/"
	to				= "https://www.ideasonstage.com/es/"
	status			= 301
	force			= false
	conditions		= {Language = ["es"], Country = ["ES"]}

[[redirects]]
	from			= "/"
	to				= "https://www.ideasonstage.com/fr/"
	status			= 301
	force			= false
	conditions		= {Language = ["fr"], Country = ["FR"]}
