backend:
  backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "static/img/news" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/news" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "news_french" # Used in routes, e.g., /admin/collections/blog
    label: "French Article" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "fr.md"
    format: "toml-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "News", name: "news", widget: "hidden", default: ["general"]}
      - {label: "Date", name: "date", widget: "date", default: "", format: "YYYY-MM-DD"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Thumb", name: "banner", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "news_english" # Used in routes, e.g., /admin/collections/blog
    label: "English Article" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "en.md"
    format: "toml-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "News", name: "news", widget: "hidden", default: ["general"]}
      - {label: "Date", name: "date", widget: "date", default: "", format: "YYYY-MM-DD"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Thumb", name: "banner", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "news_spanish" # Used in routes, e.g., /admin/collections/blog
    label: "Spanish Article" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "es.md"
    format: "toml-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "News", name: "news", widget: "hidden", default: ["general"]}
      - {label: "Date", name: "date", widget: "date", default: "", format: "YYYY-MM-DD"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Thumb", name: "banner", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"} 
  - name: "news_italian" # Used in routes, e.g., /admin/collections/blog
    label: "Italian Article" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "it.md"
    format: "toml-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Draft", name: "draft", widget: "boolean", default: "false"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "News", name: "news", widget: "hidden", default: ["general"]}
      - {label: "Date", name: "date", widget: "date", default: "", format: "YYYY-MM-DD"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Thumb", name: "banner", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"} 
