
# redirect language (only from homepage, don't redirect on subpages)

[[redirects]]
	from			= "/"
	to				= "https://www.ideasonstage.es/"
	status			= 301
	force			= false
	conditions		= {Language = ["es"], Country = ["ES"]}

[[redirects]]
	from			= "/"
	to				= "https://www.ideasonstage.fr/"
	status			= 301
	force			= false
	conditions		= {Language = ["fr"], Country = ["FR"]}
	
[[redirects]]
	from			= "/"
	to				= "https://www.ideasonstage.it/"
	status			= 301
	force			= false
	conditions		= {Language = ["it"], Country = ["IT"]}
